# Generated by Django 5.2.9 on 2026-03-06 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgets', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='budget',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='budget',
            name='title',
        ),
        migrations.AddField(
            model_name='budget',
            name='month',
            field=models.DateField(auto_now=True),
        ),
    ]
