# Generated by Django 5.2.9 on 2026-03-06 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgets', '0002_remove_budget_created_at_remove_budget_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budget',
            name='month',
            field=models.DateField(auto_now_add=True),
        ),
    ]
