# Generated by Django 5.2.9 on 2026-03-06 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgets', '0003_alter_budget_month'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budget',
            name='month',
            field=models.DateField(),
        ),
    ]
